#polling config
scan_interval: 180                              # in minutes. How often storage is scanned to sync with remote identities data
remote_protocols:                               # which kind of remote protocols poller must handle
  - email
  - imap
  - twitter
  - mastodon
#storage facility
store_name: cassandra                           # backend for remote identities data
store_settings:
  hosts: # many allowed
  - cassandra
  keyspace: caliopen
  consistency_level: 1
#messaging system
nats_url: nats://nats:4222
nats_queue : IDpoller
nats_topics:                                 # NATS topics to work with
  id_cache: idCache                          # receiving orders to update poller's cache
  imap: imapJobs                             # receiving requests for IMAP jobs
  twitter: twitterJobs                       # receiving requests for Twitter jobs